# Generated by Django 4.0.5 on 2022-10-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='media')),
                ('date', models.DateField()),
                ('writer_name', models.CharField(max_length=100)),
                ('writer_image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=300)),
                ('News_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('News_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('writer_name', models.CharField(max_length=100)),
                ('writer_image', models.ImageField(upload_to='')),
                ('about_writer', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(default=1, max_length=255)),
                ('News_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('News_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
        ),
    ]
