# Generated by Django 4.1.1 on 2022-10-10 13:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('News', 'News'), ('Blog', 'Blog')], max_length=5)),
                ('time', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='News-Blog')),
                ('title', models.CharField(max_length=150)),
                ('shortDes', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='blogs.tags')),
            ],
        ),
    ]
