# Generated by Django 4.1.1 on 2022-10-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
