# Generated by Django 4.0.5 on 2022-10-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addsubcategory',
        ),
    ]
