# Generated by Django 4.0.5 on 2022-10-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_subcategory_subcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
