# Generated by Django 4.0.5 on 2022-10-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField()),
            ],
        ),
    ]
