# Generated by Django 4.0.5 on 2022-10-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head1', models.CharField(max_length=100)),
                ('head2', models.CharField(max_length=100)),
                ('head3', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('writer_name', models.CharField(max_length=100)),
                ('writer_image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
    ]
